# Generated by Django 2.2 on 2019-04-21 15:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20190421_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='votedIN',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0), blank=True, size=None),
        ),
    ]
