# Generated by Django 2.2 on 2019-04-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
