# Generated by Django 2.2 on 2019-04-21 16:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_uservotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservotes',
            name='votedIN',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=0), size=None),
        ),
    ]
