# Generated by Django 2.2 on 2019-04-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_auto_20190426_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gradeLevel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
