# Generated by Django 2.2 on 2019-04-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_auto_20190426_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
