# Generated by Django 2.2 on 2019-04-26 20:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_auto_20190425_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choiceOrder',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionOrder',
            field=models.IntegerField(default=0),
        ),
    ]
