# Generated by Django 2.2 on 2019-04-27 00:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_auto_20190426_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
