# Generated by Django 2.2 on 2019-04-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0018_auto_20190426_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
