# Generated by Django 2.2 on 2019-04-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0019_userinfo_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionType',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('TX', 'Top X')], default='MC', max_length=2),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gradeLevel',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
