# Generated by Django 2.2 on 2019-04-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0021_auto_20190429_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
